apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oidc-egress-policy
spec:
  podSelector:
    matchLabels:
      app: oidc-provider
  policyTypes:
  - Egress
  egress:
  # Allow traffic to DNS
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow traffic to Valkey
  - to:
    - podSelector:
        matchLabels:
          app: valkey
    ports:
    - protocol: TCP
      port: 6379
  # Allow traffic to PostgreSQL Proxy (PgBouncer)
  - to:
    - podSelector:
        matchLabels:
          app: pgbouncer
    ports:
    - protocol: TCP
      port: 5432
  # Allow traffic to OpenBao
  - to:
    - podSelector:
        matchLabels:
          app: openbao
    ports:
    - protocol: TCP
      port: 8200
